In [4]:
import numpy as np

# Exercise 1 — shapes (3,) and (3,): trivial, same shape
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
print(a + b,'3')           # what do you expect before running?

# Exercise 2 — shapes (3,) and (1,): b stretches
a = np.array([1, 2, 3])
b = np.array([10])
print(a + b,'2')           # predict first

# Exercise 3 — shapes (3, 1) and (3,): this is the key one
# (3,1) + (3,) → (3,1) + (1,3) → (3,3)
col = np.array([[1], [2], [3]])    # shape (3, 1)
row = np.array([10, 20, 30])       # shape (3,)
print(col + row,'1')  

[11 22 33] 3
[11 12 13] 2
[[11 21 31]
 [12 22 32]
 [13 23 33]] 1


In [5]:
wav = np.linspace(4990,5050,1000)
wav0 = np.array([5000.0,5005.0,5010.0])
sigma = 1.0
amp = 1.0


result =  amp*np.exp(-(wav[:,np.newaxis] - wav0[np.newaxis,:])**2/(2*sigma**2))
print(result.shape)

(1000, 3)
